USE [master]
GO

/****** Object:  Database [Shopp]    Script Date: 20/11/2024 21:16:04 ******/
CREATE DATABASE [Shopp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Shopp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Shopp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Shopp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Shopp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Shopp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Shopp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Shopp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Shopp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Shopp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Shopp] SET ARITHABORT OFF 
GO

ALTER DATABASE [Shopp] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Shopp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Shopp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Shopp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Shopp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Shopp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Shopp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Shopp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Shopp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Shopp] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Shopp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Shopp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Shopp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Shopp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Shopp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Shopp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Shopp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Shopp] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Shopp] SET  MULTI_USER 
GO

ALTER DATABASE [Shopp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Shopp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Shopp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Shopp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Shopp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Shopp] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Shopp] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Shopp] SET  READ_WRITE 
GO

